# Generated by Django 4.2.16 on 2024-12-05 22:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('retailer', models.CharField(max_length=255)),
                ('purchaseDate', models.CharField(max_length=255)),
                ('purchaseTime', models.CharField(max_length=255)),
                ('items', models.JSONField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalPoints', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
